import type { AuthenticatedPropsOptions, AuthenticatedShellProps } from "./perachaAppTypes";

export function createModalProps({
  access,
  files,
  management,
  session,
  user,
}: AuthenticatedPropsOptions): AuthenticatedShellProps["modals"] {
  return {
    activeRoom: management.activeRoom,
    activeRoomId: session.activeRoomId,
    currentUserId: user.id,
    filePreviewError: files.filePreviewError,
    filePreviewUrl: files.filePreviewUrl,
    files: files.roomFiles,
    invitations: access.invitations,
    inviteEmail: access.inviteEmail,
    inviteResult: access.inviteResult,
    inviteRole: access.inviteRole,
    roomEditName: management.roomEditName,
    roomEditOpen: management.roomEditOpen,
    roomFolderOpen: files.roomFolderOpen,
    roomMembers: access.roomMembers,
    selectedFile: files.selectedRoomFile,
    userSearchLoading: access.userSearchLoading,
    userSearchQuery: access.userSearchQuery,
    userSearchResults: access.userSearchResults,
    onAddRegisteredUser: access.addRegisteredUser,
    onCloseFolder: () => files.setRoomFolderOpen(false),
    onCloseRoomEdit: () => management.setRoomEditOpen(false),
    onCreateInvitation: access.createInvitation,
    onLoadInvitations: () => access.loadInvitations(session.activeRoomId, true),
    onLoadRoomMembers: () => access.loadRoomMembers(),
    onPreviewLoadError: files.setFilePreviewError,
    onRefreshFiles: () => files.loadRoomFiles(),
    onRemoveRoomMember: access.removeRoomMember,
    onRevokeInvitation: access.revokeInvitation,
    onSearchRegisteredUsers: access.searchRegisteredUsers,
    onSelectFile: files.setSelectedRoomFile,
    onUpdateRoomDetails: management.updateRoomDetails,
    onUpdateRoomMember: access.updateRoomMember,
    setInviteEmail: access.setInviteEmail,
    setInviteRole: access.setInviteRole,
    setRoomEditName: management.setRoomEditName,
    setUserSearchQuery: access.setUserSearchQuery,
  };
}
